default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: prxy_li_development

test:
  <<: *default
  database: prxy_li_test

production:
  url: <%= ENV["DATABASE_URL"] %>
